//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DSParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DSParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDSParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DSParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.label_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_block([NotNull] DSParser.Label_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DSParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_stmt([NotNull] DSParser.Import_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.dialogue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDialogue_stmt([NotNull] DSParser.Dialogue_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.menu_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenu_stmt([NotNull] DSParser.Menu_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.menu_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenu_item([NotNull] DSParser.Menu_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.jump_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_stmt([NotNull] DSParser.Jump_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.tour_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTour_stmt([NotNull] DSParser.Tour_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_stmt([NotNull] DSParser.Call_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] DSParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] DSParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DSParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_logical_and([NotNull] DSParser.Expr_logical_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_equality([NotNull] DSParser.Expr_equalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_comparison([NotNull] DSParser.Expr_comparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_term([NotNull] DSParser.Expr_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_factor([NotNull] DSParser.Expr_factorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_unary([NotNull] DSParser.Expr_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expr_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_primary([NotNull] DSParser.Expr_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.embedded_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbedded_expr([NotNull] DSParser.Embedded_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.embedded_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbedded_call([NotNull] DSParser.Embedded_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DSParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.fstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring([NotNull] DSParser.FstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.string_fragment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_fragment([NotNull] DSParser.String_fragmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] DSParser.ConditionContext context);
}
